services:
  ProductImageControllerOverride:
    class: Scaleflex\PrestashopFilerobot\Controller\Admin\ProductImageController
    decorates: PrestaShopBundle\Controller\Admin\ProductImageController
    arguments: [ '@ProductImageControllerOverride.inner' ]

  ProductControllerOverride:
    class: Scaleflex\PrestashopFilerobot\Controller\Admin\ProductController
    decorates: PrestaShopBundle\Controller\Admin\ProductController
    arguments: [ '@ProductControllerOverride.inner' ]

  ProductDataProviderOverride:
    class: Scaleflex\PrestashopFilerobot\Adapter\ProductDataProvider
    decorates: prestashop.adapter.data_provider.product
    arguments: [ '@ProductDataProviderOverride.inner' ]

  ImageManagerOverride:
    class: Scaleflex\PrestashopFilerobot\Adapter\ImageManager
    decorates: prestashop.adapter.image_manager
    arguments: [ '@prestashop.adapter.legacy.context' ]
