services:
  ProductImageControllerOverride:
    class: Scaleflex\PrestashopFilerobot\Controller\Admin\ProductImageController
    decorates: PrestaShopBundle\Controller\Admin\ProductImageController
    arguments: ['@ProductImageControllerOverride.inner']